### ISSUE TITLE
run Football_Prediction_Project\predictions\predictions.py error

### ISSUE THREAD

**Issue by Allen-Zengr** [mhaythornthwaite/Football_Prediction_Project#1]
Hi ,  this is a very good project, but when I try to run an error, I tring to read your code to see if I can find the problem, the error location and information are as follows.
====================================================================
Football_Prediction_Project/predictions/predictions.py", line 140, in <module>
    predictions_raw = clf.predict_proba(df_for_predictions_r)
ValueError: Found array with 0 sample(s) (shape=(0, 14)) while a minimum of 1 is required.
====================================================================

**Comment by mhaythornthwaite** [comment]
Thanks for taking interest in my project! Strange, I've run the script locally with no problems (on the same commit as currently loaded to GitHub). From the error message, it appears df_for_predictions_r does not contain any data. This df should contain one row per game that we wish to predict. Please check to see that the data has loaded properly in line 79 - 'df_ml_10', and that the 'unplayed_games' df in line 74 is also populated. If this has loaded correctly then the issue may reside in the code between lines 83-132 where we use the unplayed_games and the df_ml_10 to create our final df ready to feed into the classifier.
