### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lPauI** [mhaythornthwaite/Football_Prediction_Project#11]
Hello. Can you try to do that for SuperLiga in Romania?

**Comment by mhaythornthwaite** [comment]
Hi IPaul, The code base is entirely open source, if you are interested in exploring other football leagues feel free to clone this project and play around yourself (the project is currently setup to collect data from api-football, you would need to explore this api to check if the league data was available). I'm currently maintaing this repository but I have no plans at the moment to expand it to perform predictions on other leagues.
