### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by REALLMOD** [mhaythornthwaite/Football_Prediction_Project#7]
How to put the api, 
I put the correct API and it show error 403

**Comment by mhaythornthwaite** [comment]
403 is an auth error. You'll need to signup to api-football and create an API key that you can pass into the request. Visit the following website and read the docs on how to create a key, you can signup for free and get 100 calls a day which is plenty:
https://www.api-football.com/

**Comment by REALLMOD** [comment]
> 403 is an auth error. You'll need to signup to api-football and create an API key that you can pass into the request. Visit the following website and read the docs on how to create a key, you can signup for free and get 100 calls a day which is plenty: https://www.api-football.com/

I'm trying getting free API but showing VPN or proxy issue 
Can you help me and send send one free Football API key to my email

**Comment by mhaythornthwaite** [comment]
I’m afraid I can’t do that, if you’re having trouble getting an API key please contact support on ‘api-football’. I’m going to close this ticket now as the issue is around key generation which is out of my hands.
